containers:
  basic:
    foam-extend:
      os:
        distro: ubuntu
        version: 24.04
      mpi:
        implementation: openmpi
        version: 4.1.5
      framework:
        definition: foam-extend
        version: 5.0
        git_ref: master
  projects:
    odw:
      base_container: foam-extend
      definition: apptainer/odw.def
      build_args:
        go_version:
          - 1.22.4
        hugo_version:
          - 0.130.0
pull:
  try_to_pull: true
  protocol: "oras"
  scope: "ghcr.io/foamscience"
